version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: bosta-db
    restart: always
    environment:
      POSTGRES_USER: bostauser
      POSTGRES_PASSWORD: bostapass
      POSTGRES_DB: bostadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
